### ISSUE TITLE
Social Login and additional Registration Field

### ISSUE THREAD

**Issue by hereyubaraj** [naxadeve/FactsAndroid#14]
- [x] Gmail Login / Logout
- [x] Profile information - Name , Photo
- [x] Facebook Login / Logout

**Comment by hereyubaraj** [comment]
@manishadk please add the design after the social login success. we need the API to post the user detail.

**Comment by hereyubaraj** [comment]
API for the user creation sample

Method: POST
body 
```{
         "name":"Yubaraj Poudel", 
         "email": "hereyubaraj@gmail.com",
         "gender": "male",
         "photo_url": "",
         "provider": "facebook",
         "token": "2321321323"
     }
 ```
After the request success the response should be like
```
  { 
     "success": true,
     "data": {
         ...............
    }
   }
```

If request failed
```
  { 
     "success": false,
     "message": "User creation failed "
   }
```

**Comment by manishadk** [comment]
I will ask the developer to design the api as per your screenshot @hereyubaraj
