### ISSUE TITLE
Poll of the day / UI / Functionality

### ISSUE THREAD

**Issue by manishadk** [naxadeve/FactsAndroid#6]
**UI for poll of the day**
 
- [ ] Poll of the day result view after submission
- [ ] Survey UI (Step wise scroll)
- [ ] JSON format fixed for polls and surveys

**Comment by hereyubaraj** [comment]
@manishadk How about creating dummy API instead of fix api, so later on only require to simple change in server.

**Comment by manishadk** [comment]
Sure @hereyubaraj , lets do that !
