### ISSUE TITLE
Deeplink addition

### ISSUE THREAD

**Issue by hereyubaraj** [naxadeve/FactsAndroid#63]

**Comment by hereyubaraj** [comment]
**deeplink sample**

  - factsnepal://survey
  - factsnepal://feeds  [feeds list]
  - factsnepal://feeds?id=1  [feed detail if id 1]

**Comment by konishon** [comment]
- Opens survey
`-  adb shell am start -a android.intent.action.VIEW \ -d "factsnepal://survey" np.com.naxa.factsnepal`
- Opens fact detail
`-  adb shell am start -a android.intent.action.VIEW \ -d "factsnepal://detail?id=1" np.com.naxa.factsnepal`
- Opens feed
`-  adb shell am start -a android.intent.action.VIEW \ -d "factsnepal://facts" np.com.naxa.factsnepal`

**Comment by konishon** [comment]
@hereyubaraj https://stackoverflow.com/questions/25884954/deep-linking-and-multiple-app-instances/25997627#25997627

What solution do you think is good enough ?
